export interface Theme {
  name: string;
  colors: {
    primaryBlue: string;
    primaryBlueDark: string;
    primaryBlueLight: string;
    secondaryGray: string;
    secondaryGrayLight: string;
    secondaryGrayDark: string;
    accentGreen: string;
    accentGreenLight: string;
    accentOrange: string;
    accentOrangeLight: string;
    accentRed: string;
    accentRedLight: string;
    bgPrimary: string;
    bgSecondary: string;
    bgTertiary: string;
    textPrimary: string;
    textSecondary: string;
    textTertiary: string;
    textLight: string;
    textMuted: string;
    borderLight: string;
    borderMedium: string;
    borderDark: string;
  };
}

export const themes: Record<string, Theme> = {
  blue: {
    name: 'Blue Theme',
    colors: {
      primaryBlue: '#2563eb',
      primaryBlueDark: '#1d4ed8',
      primaryBlueLight: '#3b82f6',
      secondaryGray: '#64748b',
      secondaryGrayLight: '#94a3b8',
      secondaryGrayDark: '#475569',
      accentGreen: '#10b981',
      accentGreenLight: '#34d399',
      accentOrange: '#f59e0b',
      accentOrangeLight: '#fbbf24',
      accentRed: '#ef4444',
      accentRedLight: '#f87171',
      bgPrimary: '#ffffff',
      bgSecondary: '#f8fafc',
      bgTertiary: '#f1f5f9',
      textPrimary: '#0f172a',
      textSecondary: '#475569',
      textTertiary: '#64748b',
      textLight: '#ffffff',
      textMuted: '#94a3b8',
      borderLight: '#e2e8f0',
      borderMedium: '#cbd5e1',
      borderDark: '#94a3b8',
    },
  },
  green: {
    name: 'Theme 2',
    colors: {
      primaryBlue: '#059669',
      primaryBlueDark: '#047857',
      primaryBlueLight: '#10b981',
      secondaryGray: '#64748b',
      secondaryGrayLight: '#94a3b8',
      secondaryGrayDark: '#475569',
      accentGreen: '#06b6d4',
      accentGreenLight: '#22d3ee',
      accentOrange: '#f59e0b',
      accentOrangeLight: '#fbbf24',
      accentRed: '#ef4444',
      accentRedLight: '#f87171',
      bgPrimary: '#ffffff',
      bgSecondary: '#f0fdf4',
      bgTertiary: '#ecfdf5',
      textPrimary: '#0f172a',
      textSecondary: '#475569',
      textTertiary: '#64748b',
      textLight: '#ffffff',
      textMuted: '#94a3b8',
      borderLight: '#bbf7d0',
      borderMedium: '#86efac',
      borderDark: '#4ade80',
    },
  },
  purple: {
    name: 'Theme 3',
    colors: {
      primaryBlue: '#22577a',
      primaryBlueDark: '#1a4561',
      primaryBlueLight: '#2d6b8f',
      secondaryGray: '#38a3a5',
      secondaryGrayLight: '#4db3b5',
      secondaryGrayDark: '#2d8a8c',
      accentGreen: '#57cc99',
      accentGreenLight: '#6dd4a8',
      accentOrange: '#80ed99',
      accentOrangeLight: '#95f0a8',
      accentRed: '#ef4444',
      accentRedLight: '#f87171',
      bgPrimary: '#ffffff',
      bgSecondary: '#f0fdf4',
      bgTertiary: '#ecfdf5',
      textPrimary: '#0f172a',
      textSecondary: '#475569',
      textTertiary: '#64748b',
      textLight: '#ffffff',
      textMuted: '#94a3b8',
      borderLight: '#c7f9cc',
      borderMedium: '#80ed99',
      borderDark: '#57cc99',
    },
  },
  darkBlue: {
    name: 'Theme 4',
    colors: {
      primaryBlue: '#0d1321',
      primaryBlueDark: '#0a0f1a',
      primaryBlueLight: '#1d2d44',
      secondaryGray: '#3e5c76',
      secondaryGrayLight: '#748cab',
      secondaryGrayDark: '#2d4a5f',
      accentGreen: '#f0ebd8',
      accentGreenLight: '#f5f0e0',
      accentOrange: '#748cab',
      accentOrangeLight: '#8a9db8',
      accentRed: '#ef4444',
      accentRedLight: '#f87171',
      bgPrimary: '#ffffff',
      bgSecondary: '#f0ebd8',
      bgTertiary: '#f5f0e0',
      textPrimary: '#0d1321',
      textSecondary: '#1d2d44',
      textTertiary: '#3e5c76',
      textLight: '#ffffff',
      textMuted: '#748cab',
      borderLight: '#3e5c76',
      borderMedium: '#1d2d44',
      borderDark: '#0d1321',
    },
  },
  ocean: {
    name: 'Theme 5',
    colors: {
      primaryBlue: '#023047',
      primaryBlueDark: '#011a2e',
      primaryBlueLight: '#034a6b',
      secondaryGray: '#219ebc',
      secondaryGrayLight: '#8ecae6',
      secondaryGrayDark: '#1a7a94',
      accentGreen: '#ffb703',
      accentGreenLight: '#ffc233',
      accentOrange: '#fb8500',
      accentOrangeLight: '#ff9a1f',
      accentRed: '#ef4444',
      accentRedLight: '#f87171',
      bgPrimary: '#ffffff',
      bgSecondary: '#8ecae6',
      bgTertiary: '#e3f2fd',
      textPrimary: '#023047',
      textSecondary: '#219ebc',
      textTertiary: '#8ecae6',
      textLight: '#ffffff',
      textMuted: '#219ebc',
      borderLight: '#8ecae6',
      borderMedium: '#219ebc',
      borderDark: '#023047',
    },
  },
  purpleGray: {
    name: 'Theme 6',
    colors: {
      primaryBlue: '#22223b',
      primaryBlueDark: '#1a1a2e',
      primaryBlueLight: '#2a2a4a',
      secondaryGray: '#4a4e69',
      secondaryGrayLight: '#9a8c98',
      secondaryGrayDark: '#3a3e59',
      accentGreen: '#c9ada7',
      accentGreenLight: '#d4b8b2',
      accentOrange: '#f2e9e4',
      accentOrangeLight: '#f5ede8',
      accentRed: '#ef4444',
      accentRedLight: '#f87171',
      bgPrimary: '#ffffff',
      bgSecondary: '#f2e9e4',
      bgTertiary: '#f8f6f4',
      textPrimary: '#22223b',
      textSecondary: '#4a4e69',
      textTertiary: '#9a8c98',
      textLight: '#ffffff',
      textMuted: '#c9ada7',
      borderLight: '#c9ada7',
      borderMedium: '#9a8c98',
      borderDark: '#4a4e69',
    },
  },
  oceanTeal: {
    name: 'Theme 7',
    colors: {
      primaryBlue: '#05668d',
      primaryBlueDark: '#045275',
      primaryBlueLight: '#0678a8',
      secondaryGray: '#028090',
      secondaryGrayLight: '#0398b0',
      secondaryGrayDark: '#026d7a',
      accentGreen: '#00a896',
      accentGreenLight: '#00c4a8',
      accentOrange: '#02c39a',
      accentOrangeLight: '#03d4a8',
      accentRed: '#ef4444',
      accentRedLight: '#f87171',
      bgPrimary: '#ffffff',
      bgSecondary: '#f0f3bd',
      bgTertiary: '#f8f9e0',
      textPrimary: '#05668d',
      textSecondary: '#028090',
      textTertiary: '#00a896',
      textLight: '#ffffff',
      textMuted: '#02c39a',
      borderLight: '#f0f3bd',
      borderMedium: '#02c39a',
      borderDark: '#00a896',
    },
  },
  master: {
    name: 'Theme Master',
    colors: {
      primaryBlue: '#22577a',
      primaryBlueDark: '#1a4561',
      primaryBlueLight: '#2d6b8f',
      secondaryGray: '#38a3a5',
      secondaryGrayLight: '#4db3b5',
      secondaryGrayDark: '#2d8a8c',
      accentGreen: '#57cc99',
      accentGreenLight: '#6dd4a8',
      accentOrange: '#80ed99',
      accentOrangeLight: '#95f0a8',
      accentRed: '#ef4444',
      accentRedLight: '#f87171',
      bgPrimary: '#ffffff',
      bgSecondary: '#f0fdf4',
      bgTertiary: '#ecfdf5',
      textPrimary: '#0f172a',
      textSecondary: '#475569',
      textTertiary: '#64748b',
      textLight: '#ffffff',
      textMuted: '#94a3b8',
      borderLight: '#c7f9cc',
      borderMedium: '#80ed99',
      borderDark: '#57cc99',
    },
  },
};

export type ThemeKey = keyof typeof themes;
